### ISSUE TITLE
Sync problem at begining of a loop

### ISSUE THREAD

**Issue by mrpropre** [turingmachine/omxplayer-sync#47]
I have a problem running omxplayer-sync in my Slave raspberry pi.
It try to re-sync and pause the movie every beginning of a loop.

After 5 second11, I see this brief message:

"Pause 00:00:05 / 00:01:00"
"seek 00:00:08 / 00:01:00"

and next second:

"Play 00:00:09 / 00:01:00"

The problem is that this re-sync is very noticeable on the screen...
(see here: http://raphael.isdant.free.fr/videos/sync-pb.m4v)
I use raspberry Pi 2 and 3 connected using ethernet cable, no other files in the video folder. It happens also with other video at another timecode...

Thanks for your help

**Comment by turingmachine** [comment]
The switch from one video to the next is still something that is hard to optimize because a new omxplayer instance needs to started for each video. For now re-sync between video an happen.

If you disable the verbose mode of omxplayer-sync, i.e. do not pass the -v flag, it will also not display any timecodes on the display while syncing. It would still sync, but without the times shown on screen.
