### ISSUE TITLE
Omxplayer won't respond to keyboard interrupt

### ISSUE THREAD

**Issue by vanDemonian** [turingmachine/omxplayer-sync#52]
I have omxplayer-sync working well on Raspbian Jessie 2016-09-23.
when I run "omxplayer-sync -mu /path/to/Video/vid.mp4" the file plays back perfectly
however I cannot use the keyboard to interrupt the playback.

Is there a way to overcome this limitation, as I am building a "kiosk" player for a gallery install
and need this functionality at times?

Also many thanks for working on this project is greatly appreciated.

**Comment by magdesign** [comment]
Check to code on line 161:
https://github.com/turingmachine/omxplayer-sync/blob/master/omxplayer-sync#L161

key input is disabled.

**Comment by turingmachine** [comment]
The --no-keys options is there to prevent a certain bug in omxplayer, which is probable fixed by now. Even if you wouldn't pass this option, omxplayer-sync would still need to capture keyboard keypresses and forward them to omxplayer, most probably using the dbus interface. But this feature is not implemented yet. So to answer your question: it possible, but needs to be implemented. Pull requests are welcome!

**Comment by vanDemonian** [comment]
Thanks for the responses. The main reason I would like keyboard interrupt is for debugging.
I've been getting around this by shutting down and mounting the sd card on another pi, and getting access to dhcpcd.conf, rc.local etc via that method.

I'll open a pull request but its not urgent : ) besides its almost xmas - have a good one!

**Comment by magdesign** [comment]
is this still an issue ?

**Comment by vanDemonian** [comment]
> is this still an issue ?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/turingmachine/omxplayer-sync/issues/52#issuecomment-272027065

now closed - thanks for reminding me
and thanks for the support

regards

Martin
